/** Static inputs for the seeder, kept apart from the logic that uses them. */

export const ROLES = [
  "Engineering Manager",
  "Senior Backend Engineer",
  "Product Designer",
  "Frontend Engineer",
  "Data Analyst",
  "QA Lead",
  "DevOps Engineer",
  "Product Manager",
  "UX Researcher",
  "Solutions Architect",
] as const;

/** Used when JSONPlaceholder is unreachable, so seeding works offline. */
export const FALLBACK_ROSTER = [
  { name: "Leanne Graham", email: "leanne.graham@example.com" },
  { name: "Ervin Howell", email: "ervin.howell@example.com" },
  { name: "Clementine Bauch", email: "clementine.bauch@example.com" },
  { name: "Patricia Lebsack", email: "patricia.lebsack@example.com" },
  { name: "Chelsey Dietrich", email: "chelsey.dietrich@example.com" },
  { name: "Dennis Schulist", email: "dennis.schulist@example.com" },
  { name: "Kurtis Weissnat", email: "kurtis.weissnat@example.com" },
  { name: "Nicholas Runolfsdottir", email: "nicholas.runolfsdottir@example.com" },
  { name: "Glenna Reichert", email: "glenna.reichert@example.com" },
  { name: "Clementina DuBuque", email: "clementina.dubuque@example.com" },
];

export const PROJECT_BLUEPRINTS = [
  ["Atlas Billing Migration", "Move invoicing off the legacy cluster without downtime."],
  ["Orion Analytics Rollout", "Ship the self-serve reporting workspace to all paid tiers."],
  ["Helios Design System", "Consolidate three component libraries into one token set."],
  ["Vega Mobile Companion", "Native iOS and Android client for on-call responders."],
  ["Kepler Data Warehouse", "Nightly ETL into the new columnar store."],
  ["Nimbus Cost Controls", "Per-team cloud budgets with alerting before overspend."],
  ["Quasar Search Revamp", "Replace keyword matching with a ranked relevance model."],
  ["Lyra Onboarding Flow", "Cut time-to-first-value for new workspaces."],
  ["Titan Permissions Model", "Role-based access across every product surface."],
  ["Mercury Status Page", "Public incident timeline fed from internal alerting."],
  ["Cobalt Payment Retries", "Recover failed charges with smarter retry windows."],
  ["Iris Accessibility Audit", "Bring the dashboard to WCAG 2.2 AA."],
  ["Juno Audit Trail", "Immutable log of every administrative action."],
  ["Pallas Import Tooling", "Bulk CSV import with dry-run validation."],
  ["Rhea Notification Centre", "One inbox for digests, alerts and mentions."],
  ["Sirius API Gateway", "Rate limiting and key rotation for public endpoints."],
  ["Triton Offline Mode", "Queue writes locally and reconcile on reconnect."],
  ["Umbra Dark Theme", "Full theming pass across the product."],
  ["Vesta Contract Renewals", "Automate renewal reminders and quote generation."],
  ["Zephyr Latency Budget", "Bring p95 dashboard load under 400ms."],
  ["Auriga Sandbox Accounts", "Disposable environments for customer trials."],
  ["Borealis Localisation", "Ship German, French and Spanish translations."],
  ["Corvus Fraud Signals", "Flag anomalous usage before it hits invoicing."],
  ["Draco Backup Restore", "Point-in-time recovery with a tested runbook."],
  ["Eridanus Usage Metering", "Accurate per-seat and per-event counters."],
  ["Fornax Webhook Delivery", "At-least-once delivery with replay support."],
  ["Gemini SSO Support", "SAML and OIDC for enterprise workspaces."],
  ["Hydra Query Caching", "Cut warehouse spend on repeated dashboard reads."],
  ["Indus Support Console", "Give support staff scoped, audited impersonation."],
  ["Lacerta Schema Registry", "Version and validate every event payload."],
  ["Mensa Feature Flags", "Gradual rollouts with automatic rollback."],
  ["Norma Compliance Pack", "SOC 2 evidence collection on a schedule."],
  ["Octans Email Templates", "Rebuild transactional mail on a shared layout."],
  ["Phoenix Legacy Sunset", "Retire the v1 API and migrate remaining clients."],
  ["Pyxis Storage Tiering", "Move cold attachments to cheaper object storage."],
  ["Sagitta Onboarding Emails", "Behaviour-triggered lifecycle sequence."],
  ["Serpens Rate Plans", "Support usage-based and hybrid pricing."],
  ["Tucana Admin Metrics", "Internal dashboard for activation and churn."],
  ["Volans Edge Caching", "Serve static assets from regional points of presence."],
  ["Crater Incident Review", "Structured postmortems linked to affected accounts."],
  ["Dorado Seat Management", "Self-serve invite, revoke and reassign."],
  ["Grus Query Builder", "Visual filter composer for non-technical users."],
  ["Hercules Load Testing", "Repeatable load profiles in the release pipeline."],
  ["Lupus Secret Rotation", "Automated credential rotation with zero downtime."],
  ["Musca Bug Triage", "Route incoming reports by component ownership."],
  ["Perseus Trial Conversion", "In-app prompts tied to realised value."],
  ["Scutum Session Security", "Device list, revocation and suspicious-login alerts."],
  ["Vulpecula Changelog", "Publish release notes from merged pull requests."],
] as const;
